### ISSUE TITLE
User is shown PayPal overview instead of order success page

### ISSUE THREAD

**Issue by massimocode** [SMH110/Pizza-website#16]
I don't know why but when I am checking out on https://pizza-delivery-website.herokuapp.com/checkout I end up seeing some PayPal dashboard instead of the order success page. This seems like a regression.

**Comment by SMH110** [comment]
I have just test the order process, and it is working well.

**Comment by massimocode** [comment]
It seems the origin header is not being sent by Edge

**Comment by SMH110** [comment]
I have the same problem when I use edge

**Comment by SMH110** [comment]
I was trying to place an order but there was some problems
Using firexfoex  I have been redirected to paypal instead of order-success
Using chrome I have been redirected to paypal instead of order-success.
Using Edge I stuck with Processing loop

**Comment by massimocode** [comment]
I am going to finish adding E2E tests so at least we have some coverage to help prevent these kinds of regressions
