### ISSUE TITLE
User should be able to add up to 5 toppings on their pizzas 

### ISSUE THREAD

**Issue by SMH110** [SMH110/Pizza-website#22]
I would like the user to be able to add up to 5 toppings. The toppings are all the same price (depending on the pizza size). For example extra cheese on a small pizza costs the same as extra chicken on a small pizza. But the price is different to extra cheese on a medium or large pizza.

**Comment by SMH110** [comment]
Toppings should be shown in the basket if the User adds a topping. how will the extra toppings selected be shown in the checkout? will it be a separate item? or will it come under the pizza as an additional charge?

**Comment by massimocode** [comment]
Toppings should be free on one of the pizzas. This pizza will be called "Free Choice".

**Comment by massimocode** [comment]
Multiple of the same topping can be added

**Comment by massimocode** [comment]
can add as many as they like, no limits (but free choice is only free for 5 toppings)

**Comment by massimocode** [comment]
Fixed in https://github.com/SMH110/Pizza-website/pull/131
