### ISSUE TITLE
Add  tool for checking the delivery area + validation

### ISSUE THREAD

**Issue by SMH110** [SMH110/Pizza-website#25]
I would also like some kind of tool for checking the delivery area. There should be a new page where a user can enter their postcode to check if we deliver to them. Also when they place their order, if they pick delivery then it should check if their postcode is in the list of allowed postcodes that we deliver to. I will send you a list of postcodes later on.

**Comment by massimocode** [comment]
So we've had feedback on this. There should be a link "Areas we deliver" in the top (next to Pizzas, Sides, etc) with the design you did in Invision. If the delivery area isn't supported then it should show "We don't deliver to your area. However, you can still place an order for collection."

Also, when checking out if the user's postcode is not in the delivery areas then they should get the same piece of text as an error message.

**Comment by massimocode** [comment]
Postcodes are CR7, SE15, SE19, SE21, SE22, SE23, SE24, SE26, SE27, SE5, SW12, SW16, SW17, SW2, SW4, SW8, SW9

**Comment by massimocode** [comment]
This validation should also be on the server side
