### ISSUE TITLE
Remembering user details

### ISSUE THREAD

**Issue by SMH110** [SMH110/Pizza-website#33]
I would like the system to remember the user’s checkout details once they complete the order. I don’t want them to have to create an account for this, it should just remember it on the computer they are using.

**Comment by massimocode** [comment]
The acceptance criteria for this is that if a user goes to the checkout screen and enters their buyer details (name, email, phone) and/or delivery address, then those details will be remembered in the following circumstances:
- if a user to the basket to modify their order and then back to checkout
- if a user refreshes their browser
- if a user opens the checkout in a new tab

**Comment by massimocode** [comment]
Additional clarification:

- Given the user goes to the checkout screen for the first time, and they enter some of their checkout details (as mentioned above), and they close the browser and open a new browser and go to checkout, they should NOT see their checkout details.
- Given the user goes to the checkout screen for the first time, and they enter some of their checkout details (as mentioned above), and they successfully place their order but they had checked that they do not want their details remembered, and they close the browser and open a new browser and go to checkout again, they should NOT see their checkout details.
- Given the user goes to the checkout screen for the first time, and they enter some of their checkout details (as mentioned above), and they successfully place their order, and they close the browser and open a new browser and go to checkout again, they SHOULD see their checkout details.

**Comment by SMH110** [comment]
Fixed in #223
