### ISSUE TITLE
Orders with "Complete" status should shown in one line

### ISSUE THREAD

**Issue by SMH110** [SMH110/Pizza-website#38]
I’d like to only show a single line per order which is Complete, which I can click on to expand to view the full details of the order. On the single line, I want to see the order date, amount, customer name, delivery method, payment method and total number of items.

**Comment by massimocode** [comment]
- The address should only be shown if it is delivery (there will be no address for collection)
- No order numbers should be shown
- Orders that are awaiting payment or complete should be collapsed. Awaiting payment should be in red, Outstanding in orange, and Complete in green.
- When an order is collapsed, no headers should be present and the following columns should be shown: 
    - Order Status
    - Name
    - Date
    - Address if delivery, or the word COLLECTION - the address should be clickable to bring up Google Maps in a new tab
    - Total amount paid (with payment method next to it in brackets)
    - An Expand button (this will automatically change to "Collapse" when expanded)
- When you expand an order (or if the order is not collapsed), you will see the following items appear underneath: 
    - Email address
    - Payment reference (if there is one)
    - Order notes
    - Order items in a table: 
        - Each item should have the item name (and size if applicable). Underneath the name, any additional toppings.
        - Each item should also have the quantity and price in separate columns
        - There should be a row with the order total before any discount is applied
        - And a row with the discount amount
        - And a row with the total payable (same figure as in the collapsed version)
    - Mark as Complete button if the order is not yet complete

**Comment by massimocode** [comment]
This ticket is going to stay open for now because of some feedback on https://github.com/SMH110/Pizza-website/pull/90which needs doing
