### ISSUE TITLE
Users should not be able to order when the shop is closed 

### ISSUE THREAD

**Issue by SMH110** [SMH110/Pizza-website#60]

**Comment by massimocode** [comment]
The opening times are:
Monday 11:30 – 01:00
Tuesday 11:30 – 01:00
Wednesday 11:30 – 01:00
Thursday 11:30 – 01:00
Friday 11:30 – 03:30
Saturday 11:30 – 03:30
Sunday 11:30 – 01:00

These should be listed on the contact page and there should be a shared validation (which takes in the current Date) that runs when placing orders to ensure orders are not placed outside of these hours.

**Comment by massimocode** [comment]
All 11:30 opening times should be 12:00.
